### PR TITLE
Reintegrate Adafruit IMU

### PR DESCRIPTION
**Pull request by kylecombes**
* Restructure code into class
* Publish `Vector3` orientation messages to `/boat/orientation`
* Use rospy logging

### CODE REVIEW

**Comment by kylecombes** [comment]
@noahdsouza and Jordan, can you please make sure this code still works before I merge it? To do this, please do the following on a computer that will work with the IMU:
1. `git fetch && git checkout adafruit-imu`
2. `roscore`
3. (in a new terminal) `rosrun oars_gb adafruit_imu.py`
4. (in a new terminal) `rostopic echo /boat/orientation`

**Comment by noahdsouza** [comment]
@kylecombes I don't currently have access to a raspi or the IMU, but I (or Jordan) can do this when we get back from break

**Review by noahdsouza — APPROVED** [review]
It works! I don't any changes are needed.

**Comment by kylecombes** [comment]
@noahdsouza awesome! Can you please mark the pull request as approved? There should be a green button in the top right, if you're looking at the code changes. Thanks!

**Comment by kylecombes** [comment]
I'm not sure how it says you approved this but it hasn't been fully marked as approved...

**Review by noahdsouza — APPROVED** [review]
Idk what happened but I'll try it again.

**Comment by kylecombes** [comment]
@noahdsouza, aha, I figured it out. You don't have write access to the repo. Please accept my invite and then we should be gucci.

**Comment by kylecombes** [comment]
@noahdsouza nvm you're already a part of the org, so you don't need to accept an invitation. :+1:

**Pull request merged**
